Nimb/Controllers/StoreKeeperController.cs
using FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Nimb.Models;
using NimbRepository.Model;
using NimbRepository.Model.Admin;
using NimbRepository.Model.Storekeeper;
using NimbRepository.Repository.Interfaces;

namespace Nimb.Controllers
{
    [Authorize(Roles = "Storekeeper")]
    public class StoreKeeperController : Controller
    {
        private readonly IUnitOfWork _unitOfwork;
        private IValidator<Good> _goodvalidator;
        private IValidator<Supplier> _suppvalidator;

        public StoreKeeperController(IValidator<Good> goodvalidator, IValidator<Supplier> suppvalidator, IUnitOfWork unitofwork)
        {
            _unitOfwork = unitofwork;
            _goodvalidator = goodvalidator;
            _suppvalidator = suppvalidator;
        }
        public IActionResult AddProvider()
        {
            TempData["Check"] = "keeper";

            return View();
        }
        
        public async Task<IActionResult> AddProduct()
        {
            TempData["Check"] = "keeper";
            var suppliers = new List<Supplier>(await _unitOfwork.Supplier.GetAll());

            ViewData["Suppliers"] = suppliers.Distinct();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddProduct(ProductViewModel product)
        {
            TempData["Check"] = "keeper";
            var result = await _goodvalidator.ValidateAsync(product.Good);

            var suppliers = new List<Supplier>(await _unitOfwork.Supplier.GetAll());

            ViewData["Suppliers"] = suppliers.Distinct();

            if (result.IsValid)
            {
                if (product.SuppId != 0)
                {
                    product.Good.SupplierId = product.SuppId;

                    _unitOfwork.Good.Add(product.Good);
                    _unitOfwork.Save();

                    return View("AddProduct",product);
                }
            }
            return View("AddProduct", product);
        }
        [HttpPost]
        public async Task<IActionResult> AddProviderAsync(Supplier supp)
        {
            TempData["Check"] = "keeper";
            var result = await _suppvalidator.ValidateAsync(supp);

            if (result.IsValid)
            {
                var check = await _unitOfwork.Supplier.GetAll()!;

                var existingSuppliers = check.Select(s => s.Name.ToUpperInvariant());

                var supplierName = supp.Name.ToUpperInvariant();

                if (existingSuppliers.Contains(supplierName))
                {
                    Console.WriteLine("Supplier already taken");
                }
                else
                {
                    _unitOfwork.Supplier.Add(supp);
                    _unitOfwork.Save();
                }
            }
            return View();
        }
    }
   
}

Nimb/Views/StoreKeeper/AddProduct.cshtml
@using NimbRepository.Model.Storekeeper;
@model Nimb.Models.ProductViewModel;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    IEnumerable<Supplier>? supplierList = ViewData["Suppliers"] as IEnumerable<Supplier>;
}

<link href="~/css/Storekeeper/keeperproduct.css" rel="stylesheet">




<div class="container">
    <div class="main">
        <div class="bg">
            <div class="header-container">
                <div class="header">Add product</div>
            </div>
            <form asp-action="AddProduct" asp-controller="StoreKeeper">
                <div class="inputs">
                    <select required class="supplierBox" asp-for=SuppId id="suppselectid">
                        <option selected>Choose a supplier</option>
                        @foreach (var item in supplierList!)
                        {
                            <option value=@item.Id>@Html.DisplayFor(items => item.Name)</option>
                        }
                    </select>
                    <div class="namePart">
                        <input required type="text" asp-for="Good.Name" class="nameField" id="nameField" placeholder="Enter name">
                    </div>
                    <div class="categoryPart">
                        <input required type="text" asp-for="Good.Category" class="categoryField" id="categoryField" placeholder="Enter the category">
                    </div>
                    <div class="pricePart">
                        <input required type="number" asp-for="Good.PurchasePrice" class="priceField" id="priceField" placeholder="Enter the purchase price">
                    </div>
                    <div class="pricePart">
                        <input required type="number" asp-for="Good.Rate" class="priceField" id="priceField" placeholder="Enter the rate">
                    </div>
                    <div class="countPart">
                        <input required type="number" asp-for="Good.Count" class="countField" id="countField" placeholder="Enter the count">
                    </div>
                    <div class="descPart">
                        <textarea required class="descField" asp-for="Good.Description" id="descField" placeholder="Enter the description"></textarea>
                    </div>
                </div>
                <button class="applyButton" type="submit"><p>Apply</p></button>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <script defer src="/js/keeper.js"></script>
}

Nimb/Views/StoreKeeper/AddProvider.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model NimbRepository.Model.Storekeeper.Supplier
@{
}

<link href="~/css/Storekeeper/keeperstyle.css" rel="stylesheet">

<div class="container">
    <div class="main">
        <div class="bg">
            <div class="header-container">
                <div class="header">Add supplier</div>
            </div>
            <form asp-action="AddProvider" asp-controller="StoreKeeper">
                <div class="inputs">
                    <div class="namePart">
                        <input type="text" asp-for="Name" class="nameField" id="nameField" placeholder="Enter name">
                        <br />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="categoryPart">
                        <input type="text" asp-for="Number" class="addressField" id="addressField" placeholder="Enter the number">
                        <br />
                        <span asp-validation-for="Number" class="text-danger"></span>
                    </div>
                    <div class="countPart">
                        <input type="email" asp-for="EmailAddress" class="mailField" id="mailField" placeholder="Enter the email">
                        <br />
                        <span asp-validation-for="EmailAddress" class="text-danger"></span>
                    </div>
                    <div class="pricePart">
                        <input type="text" asp-for="Address" class="priceField" id="priceField" placeholder="Enter the address">
                        <br />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                </div>
                <button class="applyButton" type="submit"><p>Apply</p></button>
            </form>
        </div>
    </div>
</div>